(define (make-account balance secret-password)
	(define (withdraw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
				balance)
			"Insufficient funds"))
	(define (deposit amount)
		(set! balance (+ balance amount))
		balance)
	(define (dispatch password mode)
		(if (eq? secret-password password)
			(cond ((eq? mode 'withdraw)
				    withdraw)
			      ((eq? mode 'deposit)
			      	deposit)
			      (else
			      	(error "Unknown request")))
			(display "Incorrect password")))
	dispatch)